import { expect, test } from '@playwright/test'

test('all panels render, rotation runs, and both estimators return output', async ({ page }) => {
  test.setTimeout(90_000)
  await page.addInitScript(() => {
    const savedFiles: string[] = []
    const savedWrites: { name: string, type: string, size: number }[] = []
    Object.assign(window, {
      __savedSweepFiles: savedFiles,
      __savedSweepWrites: savedWrites,
      showDirectoryPicker: async () => ({
        kind: 'directory', name: 'Selected parent',
        getDirectoryHandle: async (folderName: string) => {
          savedFiles.push(`folder:${folderName}`)
          const folder = {
            getDirectoryHandle: async () => folder,
            getFileHandle: async (fileName: string) => ({
              createWritable: async () => ({ write: async (value: string | Blob) => {
                savedFiles.push(fileName)
                savedWrites.push({ name: fileName, type: value instanceof Blob ? value.type : 'text/plain', size: value instanceof Blob ? value.size : value.length })
              }, close: async () => undefined }),
            }),
          }
          return folder
        },
      }),
    })
  })
  const errors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()) })
  await page.goto('/rotating-target-calibration-studio/')
  const notice = page.getByRole('dialog', { name: 'Work in progress' })
  const continueButton = page.getByRole('button', { name: 'Continue' })
  await expect(notice).toBeVisible()
  await expect(continueButton).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(continueButton).toBeFocused()
  await continueButton.click()
  await expect(notice).toBeHidden()
  await page.reload()
  await expect(notice).toBeHidden()
  const about = page.getByRole('link', { name: 'About this tool' })
  await about.click()
  await expect(notice).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(notice).toBeHidden()
  await expect(about).toBeFocused()
  await expect(page.locator('.work-marker')).toHaveText('Work in progress')
  await expect(page.locator('[data-panel]')).toHaveCount(6)
  await expect(page.locator('.brand img')).toBeVisible()
  const headerControl = page.locator('.header-play')
  await expect(headerControl).toHaveText(/Pause/)
  await headerControl.hover()
  expect(await headerControl.evaluate((button) => getComputedStyle(button).color)).toBe('rgb(255, 255, 255)')
  await expect(page.getByTestId('three-scene')).toBeVisible()
  await expect(page.getByLabel('FOV opacity')).toHaveValue('0.04')
  const angle = page.getByLabel('Revolution angle')
  const before = await angle.inputValue()
  await page.waitForTimeout(1200)
  expect(await angle.inputValue()).not.toBe(before)
  await page.getByTestId('play-pause').click()
  await page.getByRole('button', { name: 'Dense camera' }).click()
  await page.getByTestId('run-estimators').click()
  await expect(page.getByTestId('estimator-results').getByText('Accepted').first()).toBeVisible({ timeout: 30_000 })
  await expect(page.locator('.estimate-card')).toHaveCount(1)
  await expect(page.locator('.estimate-table tbody tr')).toHaveCount(2)
  await page.getByTestId('estimator-results').screenshot({ path: 'docs/estimation-overlay.png' })
  await page.getByRole('button', { name: 'Aperture ablation' }).click()
  await page.getByLabel('Geometric boundary fit').uncheck()
  await page.getByLabel('Acquisitions').fill('300')
  await expect(page.locator('.sweep-explanation')).toContainText('full target revolution')
  await page.getByRole('button', { name: 'Run sweep' }).click()
  const review = page.getByRole('dialog', { name: 'Run acquisition sweep?' })
  await expect(review).toContainText('Single aperture')
  await expect(review.getByLabel('Sweep RPM')).toHaveValue('5')
  await expect(review.getByLabel('Sweep rotations')).toHaveValue('1')
  await expect(review.getByRole('img', { name: 'Sweep target geometry' })).toBeVisible()
  await expect(review).toContainText('Velodyne Puck Hi-Res')
  await expect(review).toContainText('Contour matching')
  await expect(review).toContainText('Estimated completion')
  await page.keyboard.press('Escape')
  await expect(review).toBeHidden()
  await expect(page.getByRole('button', { name: 'Run sweep' })).toBeFocused()
  await page.locator('.header-play').click()
  await page.getByRole('button', { name: 'Run sweep' }).click()
  await expect(review.getByRole('button', { name: 'Start and save sweep' })).toBeDisabled()
  await review.getByRole('button', { name: 'Choose parent folder' }).click()
  await expect(review).toContainText('Selected parent/rotating-target-sweep_')
  const sweepAngle = page.getByLabel('Revolution angle')
  const angleBeforeSweep = await sweepAngle.inputValue()
  await review.getByRole('button', { name: 'Start and save sweep' }).click()
  await expect(page.locator('.sweep-progress-status')).toContainText(/\d+ of 300 acquisitions/)
  await page.waitForTimeout(700)
  expect(await sweepAngle.inputValue()).not.toBe(angleBeforeSweep)
  await expect(page.locator('.table-wrap')).toBeVisible({ timeout: 45_000 })
  await expect(page.locator('.sweep-save-status')).toContainText('Saved to Selected parent/rotating-target-sweep_')
  const savedFiles = await page.evaluate(() => (window as unknown as { __savedSweepFiles: string[] }).__savedSweepFiles)
  expect(savedFiles.some((name) => name.startsWith('folder:rotating-target-sweep_'))).toBe(true)
  expect(savedFiles).toEqual(expect.arrayContaining(['sweep-results.csv', 'sweep-summary.json', 'configuration.json']))
  expect(savedFiles.some((name) => name.endsWith('-detections-and-templates.png'))).toBe(true)
  const savedWrites = await page.evaluate(() => (window as unknown as { __savedSweepWrites: { name: string, type: string, size: number }[] }).__savedSweepWrites)
  expect(savedWrites.some((item) => item.name.endsWith('-detections-and-templates.png') && item.type === 'image/png' && item.size > 10_000)).toBe(true)
  await expect(page.locator('.table-wrap').first()).toContainText('S1 · Velodyne Puck Hi-Res')
  await page.locator('.sweep-block').screenshot({ path: 'docs/sweep-results.png' })
  expect(errors).toEqual([])
})

test('target edits update both 3D views and keep hub radii consistent', async ({ page }) => {
  await page.goto('/rotating-target-calibration-studio/')
  await page.getByRole('button', { name: 'Continue' }).click()
  const scene = page.getByTestId('three-scene')
  const rotation = page.getByTestId('rotation-view')
  await expect(rotation).toBeVisible()
  const presetBounds = await page.locator('.preset-row').boundingBox()
  const previewBounds = await page.locator('.target-preview').boundingBox()
  expect(Math.abs((presetBounds?.y ?? 0) - (previewBounds?.y ?? 0))).toBeLessThan(2)
  const apertureBounds = await page.locator('.aperture-row').last().boundingBox()
  const readoutBounds = await page.locator('.readout-grid').boundingBox()
  expect((readoutBounds?.y ?? 0) - ((apertureBounds?.y ?? 0) + (apertureBounds?.height ?? 0))).toBeLessThanOrEqual(12)
  await expect(page.getByRole('button', { name: 'Dual aperture', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Single aperture', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Single aperture', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: 'Dual aperture', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await page.getByRole('button', { name: 'Dual aperture', exact: true }).click()
  await page.getByLabel('Inner radius').first().fill('80')
  for (const [label, value] of [['Outer diameter', '460'], ['Hub radius', '65'], ['Plate thickness', '5']] as const) {
    const before = await scene.getAttribute('data-target-signature')
    await page.getByLabel(label).fill(value)
    await expect(scene).not.toHaveAttribute('data-target-signature', before ?? '')
    await expect(rotation).toHaveAttribute('data-target-signature', await scene.getAttribute('data-target-signature') ?? '')
  }
  for (const [label, value] of [['Width', '48'], ['Centre', '22'], ['Inner radius', '90']] as const) {
    const before = await scene.getAttribute('data-target-signature')
    await page.getByLabel(label).first().fill(value)
    await expect(scene).not.toHaveAttribute('data-target-signature', before ?? '')
  }
  const hubs = await page.locator('[data-hub-radius-mm]').evaluateAll((nodes) => nodes.map((node) => node.getAttribute('data-hub-radius-mm')))
  expect(new Set(hubs).size).toBe(1)
  await page.getByRole('button', { name: 'Dual aperture', exact: true }).click()
  await page.locator('.sensor-card select').first().selectOption('hdl-32e')
  await expect(page.locator('.sensor-card').first()).toContainText('360° annular band')
  await expect(page.locator('.sensor-view').first()).toContainText('Rings in band')
  await expect(page.locator('.sensor-view').first()).toContainText(/Rings in band\s*18/)
  await expect(page.getByLabel('Pitch')).toHaveCount(0)
  await page.locator('.sensor-card select').first().selectOption('livox-mid360')
  await expect(page.locator('.sensor-card').first()).toContainText('Asymmetric rotating band')
  await expect(page.locator('.sensor-card').first()).toContainText('Target coverage: clipped')
  await expect(page.getByLabel('Pitch').first()).toHaveValue('0')
  await page.getByRole('button', { name: /Centre on target/ }).click()
  await expect(page.getByLabel('Pitch').first()).toHaveValue('-22.5')
  await expect(page.locator('.sensor-card').first()).toContainText('Target coverage: full')
})

test('three sensors run for 60 seconds without console errors', async ({ page }) => {
  test.setTimeout(90_000)
  const errors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()) })
  await page.goto('/rotating-target-calibration-studio/')
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByRole('button', { name: 'Add sensor' }).click()
  await expect(page.locator('.sensor-view')).toHaveCount(3)
  const firstBand = page.locator('.sensor-view').first().locator('.tile-readouts strong').first()
  await expect(firstBand).not.toHaveText('0', { timeout: 30_000 })
  await page.waitForTimeout(60_000)
  await expect(firstBand).not.toHaveText('0')
  expect(errors).toEqual([])
})
